Areas/Admin/Controllers/ManageRecipesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using SelfChef.Areas.Admin.ViewModels;
using SelfChef.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SelfChef.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class ManageRecipesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _manager;
        private readonly IWebHostEnvironment _webHostEnvironment;
        public ManageRecipesController(ApplicationDbContext context, UserManager<ApplicationUser> manager, IWebHostEnvironment webHostEnvironment)
        {
            _manager = manager;
            _context = context;
            this._webHostEnvironment = webHostEnvironment;
        }

        public IActionResult Index(string searchString)
        {
            var recipes = from m in _context.Recipes.Where(r => r.Status == "Approved")
                                        select m;
            if (!String.IsNullOrEmpty(searchString))
            {
                recipes = recipes.Where(s => s.Title.Contains(searchString) || s.Description.Contains(searchString));
                ViewBag.query = searchString;
            }
            var tables = new RecipesViewModel
            {
                Recipes = recipes.ToList(),
                Users = _manager.Users
            };
            return View(tables);
        }

        [Authorize]
        public async Task<IActionResult> Delete(int id)
        {
            var user = await _manager.GetUserAsync(HttpContext.User);
            var recipe = await _context.Recipes.FindAsync(id);
            if (user.Id == recipe.Author || await _manager.IsInRoleAsync(user, "Admin"))
            {
                _context.Recipes.Remove(recipe);
                _context.SaveChanges();
                var reviews = _context.RecipeReviews.Where(a => a.RecipeID == id).ToList();
                foreach (var review in reviews)
                {
                    _context.RecipeReviews.Remove(review);
                    _context.SaveChanges();

                    var votes = _context.ReviewVotes.Where(a => a.ReviewID == review.ReviewID).ToList();
                    foreach (var vote in votes)
                    {
                        _context.ReviewVotes.Remove(vote);
                        _context.SaveChanges();
                    }
                }
                var favorites = _context.Favorites.Where(a => a.RecipeID == id).ToList();
                foreach (var favorite in favorites)
                {
                    _context.Favorites.Remove(favorite);
                    _context.SaveChanges();
                }
                if (System.IO.File.Exists(recipe.Picture))
                {
                    System.IO.File.Delete(recipe.Picture);
                    return Json("Picture successfully removed.");
                }
                return Json("Recipe successfully deleted.");
            }
            return Json("Not Allowed");
        }
    }
}

Controllers/RecipesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using SelfChef.Data;
using SelfChef.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace SelfChef.Controllers
{
    public class RecipesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _manager;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public RecipesController(ApplicationDbContext context, UserManager<ApplicationUser> manager, IWebHostEnvironment webHostEnvironment)
        {
            _manager = manager;
            _context = context;
            this._webHostEnvironment = webHostEnvironment;
        }

        [Authorize]
        public IActionResult AddOrEdit(int? id)
        {
            if (id == null)
            {
                ViewBag.edit = 0;
                return View(new Recipes());
            }
            else
            {
                var recipe = _context.Recipes.Find(id);
                if (recipe == null)
                {
                    return NotFound();
                }

                ViewBag.edit = 1;
                return View(recipe);
            }
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> AddOrEdit(int id, Recipes recipe, List<string> categories, List<string> cuisines)
        {
            var user = await _manager.GetUserAsync(HttpContext.User);
            recipe.Category = "";
            foreach (string category in categories)
            {
                recipe.Category += category + Environment.NewLine;
            }
            recipe.Cuisine = "";
            foreach (string cuisine in cuisines)
            {
                recipe.Cuisine += cuisine + Environment.NewLine;
            }
            recipe.Author = user.Id;
            recipe.ModifiedDate = @DateTime.Now;
            if (recipe.Picture != null)
            {
                var pathSplit = recipe.Picture.Split("recipes/");
                recipe.PictureName = pathSplit[1];
            }
            recipe.Status = "Pending";
            if (id == 0)
            {
                _context.Add(recipe);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index), "Home");
            }
            else
            {
                if (user.Id == recipe.Author || await _manager.IsInRoleAsync(user, "Admin"))
                {
                    _context.Update(recipe);
                    _context.SaveChanges();
                    return RedirectToAction(nameof(Index), "Home");
                }
                return NotFound();
            }
        }

        public async Task<IActionResult> UploadImage(IFormFile file)
        {
            string wwwRootPath = _webHostEnvironment.WebRootPath;
            string fileName = Path.GetFileNameWithoutExtension(file.FileName);
            string extension = Path.GetExtension(file.FileName);
            fileName = fileName + DateTime.UtcNow.ToString("yymmssfff") + extension;
            string path = Path.Combine(wwwRootPath + "/img/recipes/", fileName);
            using (var fileStream = new FileStream(path, FileMode.Create))
            {
                await file.CopyToAsync(fileStream);
            }
            return Json(path);
        }

        public IActionResult DeleteImage(int? recipeId, string path)
        {
            if (System.IO.File.Exists(path))
            {
                System.IO.File.Delete(path);
                return Json("Picture successfully removed.");
            }
            return Json("Picture doesn't exist");
                
        }

        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            else
            {
                var reviews = _context.RecipeReviews.Where(r => r.RecipeID == id).ToList();
                int sumRatings = 0;
                double sumReviews = 0;
                int avgRatings = 0;
                ViewBag.sumReviews = sumReviews;
                foreach (var review in reviews)
                {
                    sumRatings += review.Rating;
                }
                if (reviews.Count() != 0)
                {
                    avgRatings = sumRatings / reviews.Count();
                    ViewBag.sumReviews = reviews.Count();
                }
                ViewBag.avgRatings = avgRatings;
                var recipe = _context.Recipes.Find(id);
                if (recipe == null)
                {
                    return NotFound();
                }
                return View(recipe);
            }
        }

        public IActionResult ReviewsSummary(int id)
        {
            var reviews = _context.RecipeReviews.Where(r => r.RecipeID == id).ToList();
            int sumRatings = 0;
            double sumReviews = 0;
            int avgRatings = 0;
            ViewBag.sumReviews = sumReviews;
            foreach (var review in reviews)
            {
                sumRatings += review.Rating;
            }
            if (reviews.Count() != 0)
            {
                avgRatings = sumRatings / reviews.Count();
                ViewBag.sumReviews = reviews.Count();
            }
            ViewBag.avgRatings = avgRatings;
            var recipe = _context.Recipes.Find(id);
            return View(recipe);
        }

        [Authorize]
        public async Task<IActionResult> MyRecipes(string user)
        {
            var currentUser = await _manager.GetUserAsync(HttpContext.User);
            if (currentUser.Id != user)
            {
                return NotFound();
            }
            ViewBag.user = user;
            return View(_context.Recipes.Where(r => r.Author == user).ToList());
        }

        [Authorize]
        public async Task<IActionResult> Delete(int id)
        {
            var user = await _manager.GetUserAsync(HttpContext.User);
            var recipe = await _context.Recipes.FindAsync(id);
            if (user.Id == recipe.Author || await _manager.IsInRoleAsync(user, "Admin"))
            {
                _context.Recipes.Remove(recipe);
                _context.SaveChanges();
                var reviews = _context.RecipeReviews.Where(a => a.RecipeID == id).ToList();
                foreach (var review in reviews)
                {
                    _context.RecipeReviews.Remove(review);
                    _context.SaveChanges();

                    var votes = _context.ReviewVotes.Where(a => a.ReviewID == review.ReviewID).ToList();
                    foreach (var vote in votes)
                    {
                        _context.ReviewVotes.Remove(vote);
                        _context.SaveChanges();
                    }
                }
                var favorites = _context.Favorites.Where(a => a.RecipeID == id).ToList();
                foreach (var favorite in favorites)
                {
                    _context.Favorites.Remove(favorite);
                    _context.SaveChanges();
                }
                if (System.IO.File.Exists(recipe.Picture))
                {
                    System.IO.File.Delete(recipe.Picture);
                    return Json("Picture successfully removed.");
                }
                return Json("Recipe successfully deleted.");
            }
            return Json("Not Allowed");
        }
    }
}

Areas/Admin/Views/ManageRecipes/Index.cshtml
@model SelfChef.Areas.Admin.ViewModels.RecipesViewModel
@{
    ViewData["Title"] = "Admin - Manage Recipes";
    ViewData["PageName"] = "Manage Recipes";
}

<div class="row">
    <div class="col mt-4">
        <h3 class="ml-2">Manage Recipes</h3>
        <div class="row">
            <form asp-area="Admin" asp-controller="ManageRecipes" asp-action="Index">
                <div class="col-lg-12 p-3">
                    <div class="input-group ml-auto" style="width: 25em">
                        <input type="text" name="SearchString"
                               class="form-control"
                               id="inlineFormInputGroupUsername2"
                               value="@ViewBag.query"
                               placeholder="Search for Recipes.." />
                        <div class="input-group-prepend">
                            <button type="submit" value="Filter" class="btn btn-success rounded-right">
                                <i class="icofont-search"></i>
                            </button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
        <div class="row mt-4">
            @foreach (var recipe in Model.Recipes)
            {
                var user = Model.Users.Where(u => u.Id == recipe.Author).FirstOrDefault();
                <div class="col-12 col-md-6">
                    <div class="row d-flex align-items-center bg-white shadow-sm rounded m-2 p-3">
                        <div class="col-2 p-0" style="max-width: 40px">
                            <a asp-area="" asp-controller="Recipes" asp-action="Details" asp-route-id="@recipe.RecipeID" class="text-dark text-decoration-none">
                                @if (recipe.PictureName != null)
                                {
                                    <img src="@("/img/recipes/"+recipe.PictureName)"
                                         class="img-fluid rounded shadow-sm mr-3"
                                         alt="Recipe image" style="width: 40px; height: 40px;" />
                                }
                                else
                                {
                                    <img src="~/img/orange-background.jpg"
                                         class="img-fluid rounded shadow-sm mr-3"
                                         alt="Recipe image" style="width: 40px; height: 40px;" />
                                }
                            </a>
                        </div>
                        <div class="col-8">
                            <div class="row">
                                <div class="col font-weight-bold">
                                    <a asp-area="" asp-controller="Recipes" asp-action="Details" asp-route-id="@recipe.RecipeID" class="text-dark text-decoration-none">
                                        @recipe.Title
                                    </a>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col">
                                    <p class="small text-muted m-0">
                                        <a asp-area="" asp-controller="Recipes" asp-action="Details" asp-route-id="@recipe.RecipeID" class="text-dark text-decoration-none">
                                            @if (recipe.Description.Length > 30)
                                            {
                                                @(recipe.Description.Substring(0, 30))<span>...</span>
                                            }
                                            else
                                            {
                                                @recipe.Description
                                            }
                                        </a>
                                    </p>
                                    <p class="m-0 mt-1">
                                        @if (user == null)
                                        {
                                            <span class="text-muted small">By Unknown</span>
                                        }
                                        else
                                        {
                                            <span class="text-muted small">By @user.FirstName @user.LastName</span>
                                        }
                                    </p>
                                </div>
                            </div>
                        </div>
                        <div class="col">
                            <div class="dropdown float-right">
                                <a class="btn btn-link p-0" href="javascript:void(0)" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
                                    <span class="font-weight-bold">&#8942;</span>
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink" style="min-width: 0px">
                                    <li><a class="dropdown-item" asp-area="" asp-controller="Recipes" asp-action="AddOrEdit" asp-route-id="@recipe.RecipeID">Edit</a></li>
                                    <li><button class="dropdown-item" onclick="deleteRecipe('@Url.Action("Delete","ManageRecipes", new {id=recipe.RecipeID}, Context.Request.Scheme)')">Delete</button></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            }
            @if (Model.Recipes.Count() == 0)
            {
                <div class="col center-block text-center align-self-center" style="margin-top: 10%">
                    <h4 class="text-secondary">Sorry, No Recipes Added :(</h4>
                </div>
            }
        </div>
    </div>
</div>

@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
    <script src="~/js/myrecipes.js"></script>
}