Models/Favorites.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace SelfChef.Models
{
    public class Favorites
    {
        [Key]
        [Display(Name = "Author")]
        public string AuthorID { get; set; }

        [Key]
        [Display(Name = "Recipe")]
        public int RecipeID { get; set; }
    }
}

ViewModels/FavoritesViewModel.cs
using SelfChef.Data;
using SelfChef.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SelfChef.ViewModels
{
    public class FavoritesViewModel
    {
        public IEnumerable<Favorites> Favorites { get; set; }
        public IEnumerable<Recipes> Recipes { get; set; }
    }
}

Controllers/FavoritesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using SelfChef.Data;
using SelfChef.Models;
using SelfChef.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SelfChef.Controllers
{
    public class FavoritesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _manager;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public FavoritesController(ApplicationDbContext context, UserManager<ApplicationUser> manager, IWebHostEnvironment webHostEnvironment)
        {
            _manager = manager;
            _context = context;
            this._webHostEnvironment = webHostEnvironment;
        }

        [Authorize]
        public async Task<IActionResult> Index(string user)
        {
            var currentUser = await _manager.GetUserAsync(HttpContext.User);
            if (currentUser.Id != user)
            {
                return NotFound();
            }
            var tables = new FavoritesViewModel
            {
                Favorites = _context.Favorites.Where(v => v.AuthorID == user).ToList(),
                Recipes = _context.Recipes.ToList()
            };
            ViewBag.user = user;
            return View(tables);
        }

        public IActionResult FavoritesList(string user)
        {
            var tables = new FavoritesViewModel
            {
                Favorites = _context.Favorites.Where(v => v.AuthorID == user).ToList(),
                Recipes = _context.Recipes.ToList()
            };
            ViewBag.user = user;
            return View(tables);
        }

        [HttpGet]
        public IActionResult AddToFavorite(int id)
        {
            ViewBag.RecipeID = id;
            return View(_context.Favorites.Where(f => f.RecipeID == id).ToList());
        }

        [HttpPost]
        [Authorize]
        public IActionResult AddToFavorites(int recipe, string user)
        {
            if (user == null)
            {
                return RedirectToAction("Details", "Recipes", new { id = recipe });
            }
            else
            {
                var favorite = _context.Favorites.Where(v => v.AuthorID == user && v.RecipeID == recipe).FirstOrDefault();
                if (favorite == null)
                {
                    favorite = new Favorites();
                    favorite.AuthorID = user;
                    favorite.RecipeID = recipe;
                    _context.Add(favorite);
                    _context.SaveChanges();
                    return Json("Recipe successfully added to favorites");
                }
                else
                {
                    _context.Favorites.Remove(favorite);
                    _context.SaveChanges();
                    return Json("Recipe successfully removed from favorites");
                }

            }
        }
    }
}

Views/Favorites/AddToFavorite.cshtml
@model IEnumerable<SelfChef.Models.Favorites>
@using Microsoft.AspNetCore.Identity
@using SelfChef.Data
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

@{
    Layout = null;
    var currentUser = await UserManager.GetUserAsync(User);
}

@*<button class="noPrint btn nav-link text-secondary float-right p-0 ml-2"><i class="icofont-share h3"></i></button>*@
<button onclick="window.print();" class="noPrint btn nav-link text-secondary float-right p-0 ml-2"><i class="icofont-print h3"></i></button>

@if (SignInManager.IsSignedIn(User))
{
    @if (Model.Where(v => v.AuthorID == currentUser.Id && v.RecipeID == ViewBag.RecipeID).FirstOrDefault() != null)
    {
        <button onclick="addToFavorites('@Url.Action("AddToFavorites","Favorites", new {recipe=ViewBag.RecipeID, user=currentUser.Id}, Context.Request.Scheme)')" class="noPrint btn nav-link text-success float-right p-0" title="Add to Favorites"><i class="icofont-heart h3"></i></button>
    }
    else
    {
        <button onclick="addToFavorites('@Url.Action("AddToFavorites","Favorites", new {recipe=ViewBag.RecipeID, user=currentUser.Id}, Context.Request.Scheme)')" class="noPrint btn nav-link text-secondary float-right p-0" title="Add to Favorites"><i class="icofont-heart h3"></i></button>
    }
}
else
{
    <a href="/Identity/Account/Login?ReturnUrl=/Recipes/Details/@ViewBag.RecipeID" class="noPrint text-secondary float-right">
        <i class="icofont-heart h3"></i>
    </a>
}

Views/Favorites/FavoritesList.cshtml
@model SelfChef.ViewModels.FavoritesViewModel

@{
    Layout = null;
}

@foreach (var favorite in Model.Favorites)
{
    <div class="col-12 col-md-6">
        <div class="row d-flex align-items-center bg-white shadow-sm rounded m-2 p-3">
            <div class="col-2 p-0" style="max-width: 40px">
                <a asp-controller="Recipes" asp-action="Details" asp-route-id="@favorite.RecipeID" class="text-dark text-decoration-none">
                    @if (Model.Recipes.Where(r => r.RecipeID == favorite.RecipeID).FirstOrDefault().PictureName != null)
                    {
                        <img src="@("/img/recipes/"+Model.Recipes.Where(r => r.RecipeID == favorite.RecipeID).FirstOrDefault().PictureName)"
                             class="img-fluid rounded shadow-sm mr-3"
                             alt="Recipe image" style="width: 40px; height: 40px;" />
                    }
                    else
                    {
                        <img src="~/img/orange-background.jpg"
                             class="img-fluid rounded shadow-sm mr-3"
                             alt="Recipe image" style="width: 40px; height: 40px;" />
                    }
                </a>
            </div>
            <div class="col-8">
                <a asp-controller="Recipes" asp-action="Details" asp-route-id="@favorite.RecipeID" class="text-dark">
                    <div class="row">
                        <div class="col font-weight-bold">
                            @Model.Recipes.Where(r => r.RecipeID == favorite.RecipeID).FirstOrDefault().Title
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <p class="small text-muted m-0">
                                @if (Model.Recipes.Where(r => r.RecipeID == favorite.RecipeID).FirstOrDefault().Description.Length > 30)
                                {
                                    @(Model.Recipes.Where(r => r.RecipeID == favorite.RecipeID).FirstOrDefault().Description.Substring(0, 30))<span>...</span>
                                }
                                else
                                {
                                    @Model.Recipes.Where(r => r.RecipeID == favorite.RecipeID).FirstOrDefault().Description
                                }
                            </p>
                        </div>
                    </div>
                </a>
            </div>
            <div class="col">
                <span class="float-right">
                    <button onclick="manageFavorites('@Url.Action("AddToFavorites","Favorites", new {recipe=ViewBag.RecipeID, user=ViewBag.user}, Context.Request.Scheme)')" class="btn nav-link text-success float-right p-0" title="Remove from Favorites"><i class="icofont-heart h3"></i></button>
                </span>
            </div>
        </div>
    </div>
}

Views/Favorites/Index.cshtml
@model SelfChef.ViewModels.FavoritesViewModel

@{
    ViewData["Title"] = "Favorites";
}

<div class="row">
    <div class="col mt-4">
        <h3 class="ml-2">My Favorites</h3>
        <div class="row mt-4">
            @foreach (var favorite in Model.Favorites)
            {
                <div class="col-12 col-md-6">
                    <div class="row d-flex align-items-center bg-white shadow-sm rounded m-2 p-3">
                        <div class="col-2 p-0" style="max-width: 40px">
                            <a asp-controller="Recipes" asp-action="Details" asp-route-id="@favorite.RecipeID" class="text-dark text-decoration-none">
                                @if (Model.Recipes.Where(r => r.RecipeID == favorite.RecipeID).FirstOrDefault().PictureName != null)
                                {
                                    <img src="@("/img/recipes/"+Model.Recipes.Where(r => r.RecipeID == favorite.RecipeID).FirstOrDefault().PictureName)"
                                         class="img-fluid rounded shadow-sm mr-3"
                                         alt="Recipe image" style="width: 40px; height: 40px;" />
                                }
                                else
                                {
                                    <img src="~/img/orange-background.jpg"
                                         class="img-fluid rounded shadow-sm mr-3"
                                         alt="Recipe image" style="width: 40px; height: 40px;" />
                                }
                            </a>
                        </div>
                        <div class="col-8">
                            <div class="row">
                                <div class="col font-weight-bold">
                                    <a asp-controller="Recipes" asp-action="Details" asp-route-id="@favorite.RecipeID" class="text-dark text-decoration-none">
                                        @Model.Recipes.Where(r => r.RecipeID == favorite.RecipeID).FirstOrDefault().Title
                                    </a>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col">
                                    <p class="small text-muted m-0">
                                        <a asp-controller="Recipes" asp-action="Details" asp-route-id="@favorite.RecipeID" class="text-dark text-decoration-none">
                                            @if (Model.Recipes.Where(r => r.RecipeID == favorite.RecipeID).FirstOrDefault().Description.Length > 30)
                                            {
                                                @(Model.Recipes.Where(r => r.RecipeID == favorite.RecipeID).FirstOrDefault().Description.Substring(0, 30))<span>...</span>
                                            }
                                            else
                                            {
                                                @Model.Recipes.Where(r => r.RecipeID == favorite.RecipeID).FirstOrDefault().Description
                                            }
                                        </a>
                                    </p>
                                </div>
                            </div>
                        </div>
                        <div class="col">
                            <span class="float-right">
                                <button onclick="manageFavorites('@Url.Action("AddToFavorites","Favorites", new {recipe=favorite.RecipeID, user=favorite.AuthorID}, Context.Request.Scheme)')" class="btn nav-link text-success float-right p-0" title="Remove from Favorites"><i class="icofont-heart h2"></i></button>
                            </span>
                        </div>
                    </div>
                </div>
            }
            @if (Model.Favorites.Count() == 0)
            {
                <div class="col center-block text-center align-self-center" style="margin-top: 10%">
                    <h4 class="text-secondary">Sorry, No Favorite Recipes :(</h4>
                </div>
            }
        </div>
    </div>
</div>

@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
    <script src="~/js/favorites.js"></script>
}