Areas/Admin/Controllers/ManageUsersController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SelfChef.Areas.Admin.Models;
using SelfChef.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SelfChef.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class ManageUsersController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _manager;
        private readonly IWebHostEnvironment _webHostEnvironment;
        public ManageUsersController(ApplicationDbContext context, UserManager<ApplicationUser> manager, IWebHostEnvironment webHostEnvironment)
        {
            _manager = manager;
            _context = context;
            _webHostEnvironment = webHostEnvironment;
        }
        public async Task<IActionResult> Index()
        {
            var currentUser = await _manager.GetUserAsync(HttpContext.User);
            var allUsersExceptCurrentUser = await _manager.Users.Where(a => a.Id != currentUser.Id).ToListAsync();
            return View(allUsersExceptCurrentUser);
        }

        public IActionResult Create()
        {
            return View(new User());
        }

        [HttpPost]
        public async Task<IActionResult> Create(User user)
        {
            if (ModelState.IsValid)
            {
                var newUser = new ApplicationUser { UserName = user.Email, Email = user.Email, FirstName = user.FirstName, LastName = user.LastName };
                var result = await _manager.CreateAsync(newUser, user.Password);
                if (result.Succeeded)
                {
                    return RedirectToAction(nameof(Index));
                }
                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError(string.Empty, error.Description);
                }
            }
            return View(user);
        }

        public IActionResult Edit(string id)
        {
            var user = _manager.Users.Where(a => a.Id == id).FirstOrDefault();
            return View(user);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(string id, ApplicationUser model)
        {
            if (ModelState.IsValid)
            {
                var user = await _context.Users.FindAsync(id);
                user.FirstName = model.FirstName;
                user.LastName = model.LastName;
                user.PhoneNumber = model.PhoneNumber;
                user.Email = model.Email;
                user.UserName = model.UserName;
                user.NormalizedEmail = model.Email.ToUpper();
                user.NormalizedUserName = model.Email.ToUpper();
                user.UserName = model.Email;
                var result = await _manager.UpdateAsync(user);
                if (result.Succeeded)
                {
                    return RedirectToAction(nameof(Index));
                }
                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError(string.Empty, error.Description);
                }
            }

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(string id)
        {
            if (ModelState.IsValid)
            {
                if (id == null)
                {
                    return Json("No user provided");
                }

                var user = await _manager.FindByIdAsync(id);
                var rolesForUser = await _manager.GetRolesAsync(user);

                if (rolesForUser.Count() > 0)
                {
                    foreach (var item in rolesForUser.ToList())
                    {
                        var result = await _manager.RemoveFromRoleAsync(user, item);
                    }
                }
                await _manager.DeleteAsync(user);

                return Json("User successfully deleted");
            }
            else
            {
                return Json("Cannot delete user");
            }
        }
    }
}

Areas/Admin/Views/ManageUsers/Create.cshtml
@model SelfChef.Areas.Admin.Models.User
@{
    ViewData["Title"] = "Admin - Add User";
    ViewData["PageName"] = "Add User";
}

<div class="row">
    <div class="col-sm-10 col-md-8 col-lg-6 mx-auto mt-4">
        <div class="osahan-signup shadow bg-white p-4 rounded">
            <div class="px-2">
                <h3 class="my-0">Add User</h3>
                <form asp-area="Admin" asp-controller="ManageUsers" asp-action="Create" method="post" class="needs-validation" novalidate>
                    <div asp-validation-summary="ModelOnly" class="form-group text-danger"></div>
                    <div class="row mt-3">
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label asp-for="FirstName">First Name <span class="text-danger">*</span></label>
                                <input asp-for="FirstName" class="form-control" required />
                                <span asp-validation-for="FirstName" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label asp-for="LastName">Last Name <span class="text-danger">*</span></label>
                                <input asp-for="LastName" class="form-control" required />
                                <span asp-validation-for="LastName" class="text-danger"></span>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label asp-for="Email">Email <span class="text-danger">*</span></label>
                        <input asp-for="Email" class="form-control" required />
                        <span asp-validation-for="Email" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Password">Password <span class="text-danger">*</span></label>
                        <input asp-for="Password" class="form-control" required />
                        <span asp-validation-for="Password" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="ConfirmPassword">Confirm Password <span class="text-danger">*</span></label>
                        <input asp-for="ConfirmPassword" class="form-control" required />
                        <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
                    </div>
                    <button type="submit" class="btn btn-success rounded btn-lg btn-block">
                        Submit
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
    <script>
        (function () {
            'use strict';
            window.addEventListener('load', function () {
                // Fetch all the forms we want to apply custom Bootstrap validation styles to
                var forms = document.getElementsByClassName('needs-validation');
                // Loop over them and prevent submission
                var validation = Array.prototype.filter.call(forms, function (form) {
                    form.addEventListener('submit', function (event) {
                        if (form.checkValidity() === false) {
                            event.preventDefault();
                            event.stopPropagation();
                        }
                        form.classList.add('was-validated');
                    }, false);
                });
            }, false);
        })();
    </script>
}

Areas/Admin/Views/ManageUsers/Edit.cshtml
@using SelfChef.Data
@model ApplicationUser
@{
    ViewData["Title"] = "Admin - Edit User";
    ViewData["PageName"] = "Edit User";
}

<div class="row">
    <div class="col-sm-10 col-md-8 col-lg-6 mx-auto mt-4">
        <div class="osahan-signup shadow bg-white p-4 rounded">
            <div class="px-2">
                <h3 class="my-0">Edit User</h3>
                <form asp-area="Admin" asp-controller="ManageUsers" asp-action="Edit" method="post" class="needs-validation" novalidate>
                    <div asp-validation-summary="ModelOnly" class="form-group text-danger"></div>
                    <input type="hidden" asp-for="Id"/>
                    <input type="hidden" asp-for="SecurityStamp"/>
                    <input type="hidden" asp-for="ConcurrencyStamp"/>
                    <div class="row mt-3">
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label asp-for="FirstName">First Name <span class="text-danger">*</span></label>
                                <input asp-for="FirstName" class="form-control" required />
                                <span asp-validation-for="FirstName" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label asp-for="LastName">Last Name <span class="text-danger">*</span></label>
                                <input asp-for="LastName" class="form-control" required />
                                <span asp-validation-for="LastName" class="text-danger"></span>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label asp-for="Email">Email <span class="text-danger">*</span></label>
                        <input asp-for="Email" type="email" class="form-control" required />
                        <span asp-validation-for="Email" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="PhoneNumber"></label>
                        <input asp-for="PhoneNumber" class="form-control" />
                        <span asp-validation-for="PhoneNumber" class="text-danger"></span>
                    </div>
                    <button type="submit" class="btn btn-success rounded btn-lg btn-block">
                        Save
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
    <script>
        (function () {
            'use strict';
            window.addEventListener('load', function () {
                // Fetch all the forms we want to apply custom Bootstrap validation styles to
                var forms = document.getElementsByClassName('needs-validation');
                // Loop over them and prevent submission
                var validation = Array.prototype.filter.call(forms, function (form) {
                    form.addEventListener('submit', function (event) {
                        if (form.checkValidity() === false) {
                            event.preventDefault();
                            event.stopPropagation();
                        }
                        form.classList.add('was-validated');
                    }, false);
                });
            }, false);
        })();
    </script>
}

Areas/Admin/Views/ManageUsers/Index.cshtml
@using SelfChef.Data
@model IEnumerable<ApplicationUser>
@{
    ViewData["Title"] = "Admin - Users";
    ViewData["PageName"] = "Users";
}

<div class="row">
    <div class="col-12 mt-4">
        <div class="row">
            <div class="col-6">
                <h3>Users</h3>
            </div>
            <div class="col-6">
                <a class="btn btn-sm btn-success float-right" asp-area="Admin" asp-controller="ManageUsers" asp-action="Create">Add User</a>
            </div>
        </div>
        <div class="row mt-4">
            <div class="col-12">
                <table id="index-table" class="table table-sm table-bordered table-hover table-striped w-100 nowrap">
                    <thead class="bg-success">
                        <tr>
                            <th></th>
                            <th></th>
                            <th>
                                First Name
                            </th>
                            <th>
                                Last Name
                            </th>
                            <th>
                                Email
                            </th>
                            <th>
                                Phone
                            </th>
                            <th>
                                ID (Internal)
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var user in Model)
                        {
                            <tr>
                                <td>
                                    <a class="detail" href="@Url.Action("Edit","ManageUsers", new {id = user.Id})">
                                        <i class="icofont-listine-dots"></i>
                                    </a>
                                </td>
                                <td>
                                    <a class="delete" href="javascript:void(0)" onclick='return deleteUser("@Url.Action("Delete", "ManageUsers", new { id = user.Id })")'>
                                        <i class="icofont-ui-delete text-danger"></i>
                                    </a>
                                </td>
                                <td>
                                    @user.FirstName
                                </td>
                                <td>
                                    @user.LastName
                                </td>
                                <td>
                                    @user.Email
                                </td>
                                <td>
                                    @user.PhoneNumber
                                </td>
                                <td>
                                    @user.Id
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
            @if (Model.Count() == 0)
            {
                <div class="col center-block text-center align-self-center" style="margin-top: 10%">
                    <h4 class="text-secondary">No Registered Users Yet</h4>
                </div>
            }
        </div>
    </div>
</div>

@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
    <script src="~/js/users.js"></script>
}