ViewModels/ReviewsViewModel.cs
using SelfChef.Data;
using SelfChef.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SelfChef.ViewModels
{
    public class ReviewsViewModel
    {
        public IEnumerable<RecipeReviews> Reviews { get; set; }
        public IEnumerable<ApplicationUser> Users { get; set; }
        public IEnumerable<ReviewVotes> ReviewVotes { get; set; }
    }
}

Controllers/ReviewsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using SelfChef.Data;
using SelfChef.Models;
using SelfChef.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SelfChef.Controllers
{
    public class ReviewsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _manager;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public ReviewsController(ApplicationDbContext context, UserManager<ApplicationUser> manager, IWebHostEnvironment webHostEnvironment)
        {
            _manager = manager;
            _context = context;
            this._webHostEnvironment = webHostEnvironment;
        }

        public IActionResult Index()
        {
            return View();
        }
        
        [Authorize]
        public async Task<IActionResult> AddOrEdit(int? recipe, int id = 0)
        {
            if (id == 0)
            {
                var user = await _manager.GetUserAsync(HttpContext.User);
                ViewBag.recipe = recipe;
                if (user != null)
                    ViewBag.author = user.Id;
                return View(new RecipeReviews());
            }
            else
            {
                var review = await _context.RecipeReviews.FindAsync(id);
                if (review == null)
                {
                    return NotFound();
                }
                var user = await _manager.GetUserAsync(HttpContext.User);
                ViewBag.recipe = recipe;
                if (user != null)
                    ViewBag.author = user.Id;
                return View(review);
            }
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> AddOrEdit(int id, RecipeReviews review)
        {
            if (ModelState.IsValid)
            {
                if (id == 0)
                {
                    review.ModifiedDate = @DateTime.Now;
                    _context.Add(review);
                    await _context.SaveChangesAsync();
                }
                else
                {
                    review.ModifiedDate = DateTime.Now;
                    _context.Update(review);
                    await _context.SaveChangesAsync();
                }
                var tables = new ReviewsViewModel
                {
                    Reviews = _context.RecipeReviews.Where(s => s.RecipeID == id).ToList(),
                    Users = _manager.Users,
                };
                return Json(new { isValid = true });
            }
            return Json(new { isValid = false, html = Helper.RenderRazorViewToString(this, "AddOrEdit", review) });
        }

        public IActionResult ViewReviews(int id)
        {
            var tables = new ReviewsViewModel
            {
                Reviews = _context.RecipeReviews.Where(s => s.RecipeID == id).ToList(),
                Users = _manager.Users,
                ReviewVotes = _context.ReviewVotes.ToList()
            };
            return View(tables);
        }

        [HttpPost]
        public IActionResult Delete(int id)
        {
            var review = _context.RecipeReviews.Find(id);
            _context.RecipeReviews.Remove(review);
            _context.SaveChanges();
            return Json("Review successfuly deleted");
        }

        [HttpPost]
        [Authorize]
        public IActionResult Helpful(int id, string user, int recipe)
        {
            if (user == null)
            {
                return RedirectToAction("Details", "Recipes", new { id = recipe });
            }
            else
            {
                var vote = _context.ReviewVotes.Where(v => v.AuthorID == user && v.ReviewID == id).FirstOrDefault();
                if (vote == null)
                {
                    vote = new ReviewVotes();
                    vote.AuthorID = user;
                    vote.ReviewID = id;
                    vote.Vote = 1;
                    _context.Add(vote);
                    _context.SaveChanges();
                    return Json("Review successfully marked as helpful");
                }
                else
                {
                    _context.ReviewVotes.Remove(vote);
                    _context.SaveChanges();
                    return Json("Review successfully marked as NOT helpful");
                }
                
            }
        }
    }
}

Views/Reviews/AddOrEdit.cshtml
@model SelfChef.Models.RecipeReviews

@{ Layout = null; }

<div class="row">
    <div class="col-md-12">
        <form asp-action="AddOrEdit" asp-route-id="@Model.ReviewID" onsubmit="return jQueryAjaxPost(this);" class="needs-validation" novalidate>
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ReviewID" />
            <input type="hidden" asp-for="RecipeID" value="@ViewBag.recipe" />
            <input type="hidden" asp-for="AuthorID" value="@ViewBag.author" />
            <div class="row">
                <div class="col-2">
                    <div class="form-group">
                        <label asp-for="Rating" class="control-label"></label>
                        <select id="rating-select" asp-for="Rating" class="custom-select" required>
                            <option value="1">1</option>
                            <option value="2">2</option>
                            <option value="3">3</option>
                            <option value="4">4</option>
                            <option value="5">5</option>
                        </select>
                        <div class="invalid-feedback">
                            Rating is required.
                        </div>
                        <span asp-validation-for="Rating" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="row mt-3">
                <div class="col">
                    <div class="form-group">
                        <label asp-for="Description" class="control-label"></label>
                        <textarea id="description" asp-for="Description" class="form-control" rows="5" placeholder="Write a detailed review (optional)."></textarea>
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="row mt-3">
                <div class="col-md-6 offset-md-3">
                    <div class="form-group">
                        <input type="submit" value="Save" class="btn btn-success btn-block" />
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

Views/Reviews/ViewReviews.cshtml
@model SelfChef.ViewModels.ReviewsViewModel
@using Microsoft.AspNetCore.Identity
@using SelfChef.Data
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

@{ 
    Layout = null;
    var currentUser = await UserManager.GetUserAsync(User);
}

@foreach (var review in Model.Reviews)
{
    var user = Model.Users.Where(u => u.Id == review.AuthorID).FirstOrDefault();
    int nbVotes = Model.ReviewVotes.Where(v => v.ReviewID == review.ReviewID).ToList().Count();
    @if (user != null)
    {
        <hr />
        <div class="mt-2">
            <div class="row">
                <div class="col-10">
                    <h6 class="mb-3">Author: @user.FirstName @user.LastName</h6>
                </div>
                @if (SignInManager.IsSignedIn(User))
                {
                    @if (currentUser.Id == user.Id || await UserManager.IsInRoleAsync(currentUser, "Admin"))
                    {
                        <div class="col-2">
                            <div class="dropdown float-right">
                                <a class="btn btn-link p-0" href="javascript:void(0)" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
                                    <span class="font-weight-bold">&#8942;</span>
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink" style="min-width: 0px">
                                    <li><button class="dropdown-item" onclick="showInPopup('@Url.Action("AddOrEdit","Reviews",new {id=review.ReviewID, recipe=review.RecipeID},Context.Request.Scheme)','Edit Review')">Edit</button></li>
                                    <li><button class="dropdown-item" onclick="jQueryAjaxDelete('@(review.ReviewID.ToString())')">Delete</button></li>
                                </ul>
                            </div>
                        </div>
                    }
                }
            </div>
            <div class="rating-wrap d-flex align-items-center mt-2">
                <ul class="rating-stars list-unstyled">
                    <li>
                        @for (int i = 0; i < review.Rating; i++)
                        {
                            <i class="icofont-star text-warning"></i>
                        }
                        @for (int i = 0; i < (5 - review.Rating); i++)
                        {
                            <i class="icofont-star"></i>
                        }
                    </li>
                </ul>
            </div>
            <p>@review.Description</p>
            <p>
                <small class="text-muted">Modified on @review.ModifiedDate.Value.ToString("dd/MM/yyyy hh:mm:ss")</small>

                @if (SignInManager.IsSignedIn(User))
                {
                    @if (Model.ReviewVotes.Where(v => v.AuthorID == currentUser.Id && v.ReviewID == review.ReviewID).FirstOrDefault() != null)
                    {
                        <a href="javascript:helpful('@Url.Action("Helpful","Reviews", new {id=review.ReviewID, user=currentUser.Id, recipe=review.RecipeID}, Context.Request.Scheme)')" class="text-dark">
                            <span class="float-right"><i class="icofont-thumbs-up h5 pr-1 text-success"></i>Helpful <small class="text-muted">(@nbVotes)</small></span>
                        </a>
                    }
                    else
                    {
                        <a href="javascript:helpful('@Url.Action("Helpful","Reviews", new {id=review.ReviewID, user=currentUser.Id, recipe=review.RecipeID}, Context.Request.Scheme)')" class="text-dark">
                            <span class="float-right"><i class="icofont-thumbs-up h5 pr-1"></i>Helpful <small class="text-muted">(@nbVotes)</small></span>
                        </a>
                    }
                }
                else
                {
                    <a href="/Identity/Account/Login?ReturnUrl=/Recipes/Details/@review.RecipeID" class="text-dark">
                        <span class="float-right"><i class="icofont-thumbs-up h5 pr-1"></i>Helpful <small class="text-muted">(@nbVotes)</small></span>
                    </a>
                }
            </p>
        </div>
    }
}